export const authModalStyles = {
  overlay: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-md animate-fade-in overflow-y-auto",
  modalCard: "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-2xl w-full max-w-md overflow-hidden relative transition-all duration-300",
  headerBanner: "bg-gradient-to-r from-indigo-600 to-purple-600 p-6 text-white relative",
  closeButton: "absolute top-4 right-4 p-2 text-white/80 hover:text-white bg-white/10 hover:bg-white/20 rounded-full transition-all cursor-pointer",
  headerBadge: "flex items-center gap-2 mb-1",
  headerBadgeIcon: "w-5 h-5 text-amber-300",
  headerBadgeText: "text-xs font-bold uppercase tracking-wider text-indigo-200",
  headerTitle: "text-xl font-extrabold tracking-tight",
  headerSubtitle: "text-xs text-indigo-100 mt-1",
  bodyContent: "p-6",
  errorAlert: "mb-4 p-3 rounded-2xl bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 flex items-start gap-2.5 text-rose-600 dark:text-rose-400 text-xs font-semibold",
  successAlert: "mb-4 p-3 rounded-2xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800 flex items-center gap-2.5 text-emerald-600 dark:text-emerald-400 text-xs font-semibold",
  formGroup: "space-y-4",
  label: "block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1",
  inputWrapper: "relative",
  inputIcon: "w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2",
  inputField: "w-full bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 rounded-xl py-2.5 pl-10 pr-4 text-xs text-slate-900 dark:text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-500",
  selectIcon: "w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none",
  selectField: "w-full bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 rounded-xl py-2.5 pl-9 pr-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-500 cursor-pointer",
  submitButton: "w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 rounded-xl text-xs transition-all shadow-md active:scale-95 flex items-center justify-center gap-2 cursor-pointer mt-2",
  footerToggle: "pt-2 text-center border-t border-slate-100 dark:border-slate-800",
  footerText: "text-xs text-slate-500 dark:text-slate-400",
  toggleButton: "text-xs font-bold text-indigo-600 dark:text-indigo-400 hover:underline cursor-pointer"
};
