export const userProfileStyles = {
  overlay: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-md animate-fade-in overflow-y-auto",
  modalCard: "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl shadow-2xl w-full max-w-2xl overflow-hidden relative transition-all duration-300",
  headerBanner: "bg-gradient-to-r from-indigo-600 via-indigo-700 to-purple-700 p-6 text-white relative",
  closeButton: "absolute top-4 right-4 p-2 text-white/80 hover:text-white bg-white/10 hover:bg-white/20 rounded-full transition-all cursor-pointer",
  avatarImage: "w-16 h-16 rounded-2xl border-2 border-white/40 bg-white/10 object-cover shadow-lg",
  userName: "text-xl font-extrabold tracking-tight",
  verifiedBadge: "bg-emerald-500/20 text-emerald-300 border border-emerald-400/30 text-[10px] font-bold px-2 py-0.5 rounded-full flex items-center gap-1",
  userSubtitle: "text-xs text-indigo-100 flex items-center gap-1.5 mt-1",
  tabsWrapper: "flex items-center gap-4 mt-6 border-b border-white/15 pb-0",
  tabButtonActive: "text-xs font-bold uppercase tracking-wider pb-2.5 transition-all cursor-pointer border-b-2 border-amber-400 text-white",
  tabButtonInactive: "text-xs font-bold uppercase tracking-wider pb-2.5 transition-all cursor-pointer border-b-2 border-transparent text-white/60 hover:text-white",
  badgeCount: "bg-white/20 text-white text-[10px] px-1.5 py-0.2 rounded-full font-extrabold ml-1.5",
  contentContainer: "p-6 max-h-[70vh] overflow-y-auto",
  dataGrid: "grid grid-cols-1 md:grid-cols-2 gap-4",
  infoCard: "p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/40 border border-slate-100 dark:border-slate-800/80",
  infoLabel: "flex items-center gap-2 text-slate-400 text-xs font-semibold mb-1",
  infoValue: "text-sm font-bold text-slate-900 dark:text-white",
  actionRow: "flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800",
  editButton: "flex items-center gap-2 text-xs font-bold text-indigo-600 dark:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-950/40 px-4 py-2.5 rounded-xl border border-indigo-200 dark:border-indigo-800/60 transition-all cursor-pointer",
  logoutButton: "flex items-center gap-2 text-xs font-bold text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/40 px-4 py-2.5 rounded-xl border border-rose-200 dark:border-rose-800/60 transition-all cursor-pointer",
  emptyContainer: "text-center py-10",
  emptyTitle: "text-xs font-bold text-slate-600 dark:text-slate-300",
  emptyText: "text-[11px] text-slate-400 mt-1",
  publicationsGrid: "grid grid-cols-1 sm:grid-cols-2 gap-4"
};
